/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import controller.PecaController;
import java.util.List;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Peca;
import utils.Util;

/**
 *
 * @author aluno.saolucas
 */
public class FrAltPeca extends javax.swing.JDialog {
    private int idPeca ;

    public int getIdPeca() {
        return idPeca;
    }

    public void setIdPeca(int idPeca) {
        this.idPeca = idPeca;
    }
    /**
     * Creates new form FrAltPeca
     */
    public FrAltPeca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAltValorPeca = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        edtAltNomePeca = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        edtAltValorPeca = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        edtAltDescricaoPeca = new javax.swing.JTextField();
        lbAltlNomePeca = new javax.swing.JLabel();
        lblAltDescricaoPeca = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Peça");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAltValorPeca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAltValorPeca.setText("VALOR:");
        jPanel1.add(lblAltValorPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        btnVoltar.setBackground(new java.awt.Color(234, 106, 106));
        btnVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        edtAltNomePeca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        edtAltNomePeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtAltNomePecaActionPerformed(evt);
            }
        });
        jPanel1.add(edtAltNomePeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 223, -1));

        btnSalvar.setBackground(new java.awt.Color(234, 106, 106));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));
        jPanel1.add(edtAltValorPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 223, -1));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setText("CADASTRO DE PEÇAS");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));
        jPanel1.add(edtAltDescricaoPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 223, -1));

        lbAltlNomePeca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbAltlNomePeca.setText("NOME:");
        jPanel1.add(lbAltlNomePeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        lblAltDescricaoPeca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAltDescricaoPeca.setText("DESCRIÇÃO:");
        jPanel1.add(lblAltDescricaoPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203520_circle_dot_record_round_icon.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 270, 70, 100));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11108091_flickr_online_social_media_icon.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 60, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203520_circle_dot_record_round_icon.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, -50, 70, 100));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11108091_flickr_online_social_media_icon.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void edtAltNomePecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtAltNomePecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtAltNomePecaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        //seta o icone
        this.setIconImage(Util.getIcone()); 

        //carregar os dados do usuario
        PecaController controler = new PecaController();
        //consultar os usuarios com o codigo igual ao que recebi
        List<Peca> lista = controler.consultar(0, String.valueOf(idPeca));

        Peca pec = lista.get(0);

        //preencher os campos como a variável 
        edtAltNomePeca.setText(pec.getNome());
        edtAltValorPeca.setText(String.valueOf(pec.getValorUnitario()));
        edtAltDescricaoPeca.setText(pec.getDescricao());
        
       
    }//GEN-LAST:event_formWindowOpened

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
       gravar();
    }//GEN-LAST:event_btnSalvarMouseClicked
    private void gravar() {
    
        if (!verificarCampos()) {
        return;
    }
        
        //ler os campos e guardar um objeto
        Peca pec = new Peca();
        pec.setNome(edtAltNomePeca.getText());
        pec.setValorUnitario(Double.parseDouble(edtAltValorPeca.getText()));
        pec.setDescricao(edtAltDescricaoPeca.getText());
        pec.setIdPeca(idPeca);
        
       
        
       
       
        
        
        //enviar para o banco de dados
       PecaController controler = new PecaController();
        if(controler.alterar(pec)){
            JOptionPane.showMessageDialog(null, "Peça Alterada");
            this.dispose();
        }
    }
    
        private boolean verificarCampos() {
    if (edtAltNomePeca.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Nome da Peça em branco!");
        return false;
    }
    if (edtAltValorPeca.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Valor Unitário em branco!");
        return false;
    }
    if (edtAltDescricaoPeca.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Descrição em branco!");
        return false;
    }

    
    try {
        Double.parseDouble(edtAltValorPeca.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Valor Unitário inválido! Digite um número.");
        return false;
    }

    return true;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAltPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAltPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAltPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAltPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrAltPeca dialog = new FrAltPeca(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField edtAltDescricaoPeca;
    private javax.swing.JTextField edtAltNomePeca;
    private javax.swing.JTextField edtAltValorPeca;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAltlNomePeca;
    private javax.swing.JLabel lblAltDescricaoPeca;
    private javax.swing.JLabel lblAltValorPeca;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
