/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import java.util.List;
import javax.swing.JOptionPane;
import model.Cliente;
import utils.Util;

/**
 *
 * @author aluno.saolucas
 */
public class FrAltCliente extends javax.swing.JDialog {

    private int idCliente;

    public int getIdCliente() {
        return idCliente;
    }

    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    /**
     * Creates new form FrAltCliente
     */
    public FrAltCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        edtNomeAltCliente = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        edtAltTelefoneCliente = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        edtAltEmailCliente = new javax.swing.JTextField();
        edtAltEnderecoCliente = new javax.swing.JTextField();
        lblNomeAltCliente = new javax.swing.JLabel();
        lblAltEmailCliente = new javax.swing.JLabel();
        lblAltEnderecoCliente = new javax.swing.JLabel();
        lblAltTelefoneCliente = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Cliente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setBackground(new java.awt.Color(234, 106, 106));
        btnVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 303, -1, -1));

        edtNomeAltCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        edtNomeAltCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeAltClienteActionPerformed(evt);
            }
        });
        jPanel1.add(edtNomeAltCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 84, 223, -1));

        btnSalvar.setBackground(new java.awt.Color(234, 106, 106));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 303, -1, -1));
        jPanel1.add(edtAltTelefoneCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 148, 223, -1));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setText("ALTERAÇÃO DE CLIENTES");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 14, -1, -1));
        jPanel1.add(edtAltEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 202, 223, -1));
        jPanel1.add(edtAltEnderecoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 261, 223, -1));

        lblNomeAltCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNomeAltCliente.setText("NOME:");
        jPanel1.add(lblNomeAltCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 61, -1, -1));

        lblAltEmailCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAltEmailCliente.setText("E-MAIL:");
        jPanel1.add(lblAltEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 184, -1, -1));

        lblAltEnderecoCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAltEnderecoCliente.setText("ENDEREÇO:");
        jPanel1.add(lblAltEnderecoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 238, -1, -1));

        lblAltTelefoneCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAltTelefoneCliente.setText("TELEFONE:");
        jPanel1.add(lblAltTelefoneCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 125, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203520_circle_dot_record_round_icon.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 300, 70, 100));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11108091_flickr_online_social_media_icon.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 60, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203520_circle_dot_record_round_icon.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, -50, 70, 100));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11108091_flickr_online_social_media_icon.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void edtNomeAltClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeAltClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeAltClienteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        //seta o icone
        this.setIconImage(Util.getIcone());

        //carregar os dados do usuario
        ClienteController controler = new ClienteController();
        //consultar os usuarios com o codigo igual ao que recebi
        List<Cliente> lista = controler.consultar(0, String.valueOf(idCliente));

        Cliente cli = lista.get(0);

        //preencher os campos como a variável usu
        edtNomeAltCliente.setText(cli.getNome());
        edtAltTelefoneCliente.setText(cli.getTelefone());
        edtAltEmailCliente.setText(cli.getEmail());
        edtAltEnderecoCliente.setText(cli.getEndereco());
    }//GEN-LAST:event_formWindowOpened

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        gravar();
    }//GEN-LAST:event_btnSalvarMouseClicked
    private void gravar() {

        if (!verificarCampos()) {
            return;
        }

        //ler os campos e guardar um objeto
        Cliente cli = new Cliente();
        cli.setIdCliente(idCliente);
        cli.setNome(edtNomeAltCliente.getText());
        cli.setTelefone(edtAltTelefoneCliente.getText());
        cli.setEmail(edtAltEmailCliente.getText());
        cli.setEndereco(edtAltEnderecoCliente.getText());

        //enviar para o banco de dados
        ClienteController controler = new ClienteController();
        if (controler.alterar(cli)) {
            JOptionPane.showMessageDialog(null, "Cliente Alterado");
            this.dispose();
        }
    }

    private boolean verificarCampos() {
        if (edtNomeAltCliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Nome em branco!");
            return false;
        }
        if (edtAltTelefoneCliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Telefone em branco!");
            return false;
        }
        if (edtAltEmailCliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo E-mail em branco!");
            return false;
        }
        if (edtAltEnderecoCliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Endereço em branco!");
            return false;
        }

        return true;
    }
        /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAltCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAltCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAltCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAltCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrAltCliente dialog = new FrAltCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField edtAltEmailCliente;
    private javax.swing.JTextField edtAltEnderecoCliente;
    private javax.swing.JTextField edtAltTelefoneCliente;
    private javax.swing.JTextField edtNomeAltCliente;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAltEmailCliente;
    private javax.swing.JLabel lblAltEnderecoCliente;
    private javax.swing.JLabel lblAltTelefoneCliente;
    private javax.swing.JLabel lblNomeAltCliente;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
