/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PecaController;
import controller.ServicoController;
import java.util.List;
import javax.swing.JOptionPane;
import model.Peca;
import model.Servico;
import utils.Util;

/**
 *
 * @author aluno.saolucas
 */
public class FrAltServico extends javax.swing.JDialog {

    /**
     * Creates new form FrAltServico
     */
    public FrAltServico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(null);
    }
    private int idServico;

    public int getIdServico() {
        return idServico;
    }

    public void setIdServico(int idServico) {
        this.idServico = idServico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        edtAltDescricaoServico = new javax.swing.JTextField();
        lblAltlNomeServico = new javax.swing.JLabel();
        lblAltDescricaoServico = new javax.swing.JLabel();
        lblAltValorServico = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        edtAltNomeServico = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        edtAltValorServico = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Serviço");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(edtAltDescricaoServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 207, 223, -1));

        lblAltlNomeServico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAltlNomeServico.setText("NOME:");
        jPanel1.add(lblAltlNomeServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 61, -1, -1));

        lblAltDescricaoServico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAltDescricaoServico.setText("DESCRIÇÃO:");
        jPanel1.add(lblAltDescricaoServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 184, -1, -1));

        lblAltValorServico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAltValorServico.setText("VALOR:");
        jPanel1.add(lblAltValorServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 125, -1, -1));

        btnVoltar.setBackground(new java.awt.Color(234, 106, 106));
        btnVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        edtAltNomeServico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        edtAltNomeServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtAltNomeServicoActionPerformed(evt);
            }
        });
        jPanel1.add(edtAltNomeServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 84, 223, -1));

        btnSalvar.setBackground(new java.awt.Color(234, 106, 106));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));
        jPanel1.add(edtAltValorServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 148, 223, -1));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setText("ALTERAÇÃO DE SERVIÇOS");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 14, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203520_circle_dot_record_round_icon.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 260, 70, 100));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11108091_flickr_online_social_media_icon.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 60, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203520_circle_dot_record_round_icon.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, -50, 70, 100));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11108091_flickr_online_social_media_icon.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void edtAltNomeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtAltNomeServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtAltNomeServicoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        //Seta o icone
        this.setIconImage(Util.getIcone());

        //carregar os dados do usuario
        ServicoController controler = new ServicoController();
        //consultar os usuarios com o codigo igual ao que recebi
        List<Servico> lista = controler.consultar(0, String.valueOf(idServico));

        Servico ser = lista.get(0);

        //preencher os campos como a variável 
        
        edtAltNomeServico.setText(ser.getNomeServico());
        edtAltValorServico.setText(String.valueOf(ser.getValorUnitario()));
        edtAltDescricaoServico.setText(ser.getDescricao());


    }//GEN-LAST:event_formWindowOpened

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        gravar();
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void gravar() {

        
        if (!verificarCampos()) {
        return;
    }
        
        //ler os campos e guardar um objeto
        Servico ser = new Servico();
        ser.setNomeServico(edtAltNomeServico.getText());
        ser.setValorUnitario(Double.parseDouble(edtAltValorServico.getText()));
        ser.setDescricao(edtAltDescricaoServico.getText());
        ser.setIdServico(idServico);

        //enviar para o banco de dados
        ServicoController controler = new ServicoController();
        if (controler.alterar(ser)) {
            JOptionPane.showMessageDialog(null, "Serviço Alterado");
            this.dispose();
        }
    }
    
    private boolean verificarCampos() {
    if (edtAltNomeServico.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Nome do Serviço em branco!");
        return false;
    }
    if (edtAltValorServico.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Valor Unitário em branco!");
        return false;
    }
    if (edtAltDescricaoServico.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Descrição em branco!");
        return false;
    }

    // Validação do valor numérico e positivo
    try {
        double valor = Double.parseDouble(edtAltValorServico.getText());
        if (valor < 0) {
            JOptionPane.showMessageDialog(null, "O valor do serviço não pode ser negativo!");
            return false;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Valor Unitário inválido! Digite um número.");
        return false;
    }

    return true;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAltServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAltServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAltServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAltServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrAltServico dialog = new FrAltServico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField edtAltDescricaoServico;
    private javax.swing.JTextField edtAltNomeServico;
    private javax.swing.JTextField edtAltValorServico;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAltDescricaoServico;
    private javax.swing.JLabel lblAltValorServico;
    private javax.swing.JLabel lblAltlNomeServico;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
