/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CarroController;
import controller.ClienteController;
import controller.PecaController;
import java.util.List;
import javax.swing.JOptionPane;
import model.Carro;
import model.Cliente;
import model.Peca;
import utils.Util;

/**
 *
 * @author aluno.saolucas
 */
public class FrAltCarro extends javax.swing.JDialog {

    private int idCarro;

    public int getIdCarro() {
        return idCarro;
    }

    public void setIdCarro(int idCarro) {
        this.idCarro = idCarro;
    }

    public FrAltCarro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        edtPlacaCarro = new javax.swing.JTextField();
        lblPlacaCarro = new javax.swing.JLabel();
        edtAnoCarro = new javax.swing.JTextField();
        lblAnoCarro = new javax.swing.JLabel();
        edtModeloCarro = new javax.swing.JTextField();
        lblModeloCarro = new javax.swing.JLabel();
        lblMarcaCarro = new javax.swing.JLabel();
        edtMarcaCarro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setBackground(new java.awt.Color(234, 106, 106));
        btnVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        btnSalvar.setBackground(new java.awt.Color(234, 106, 106));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setText("ALTERAR  CARROS");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));
        jPanel1.add(edtPlacaCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 240, -1));

        lblPlacaCarro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPlacaCarro.setText("PLACA:");
        jPanel1.add(lblPlacaCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        edtAnoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtAnoCarroActionPerformed(evt);
            }
        });
        jPanel1.add(edtAnoCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 256, 240, -1));

        lblAnoCarro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAnoCarro.setText("ANO DE FABRICAÇÃO:");
        jPanel1.add(lblAnoCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        edtModeloCarro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        edtModeloCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtModeloCarroActionPerformed(evt);
            }
        });
        jPanel1.add(edtModeloCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 228, -1));

        lblModeloCarro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblModeloCarro.setText("MODELO:");
        jPanel1.add(lblModeloCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        lblMarcaCarro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMarcaCarro.setText("MARCA:");
        jPanel1.add(lblMarcaCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));
        jPanel1.add(edtMarcaCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 228, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203520_circle_dot_record_round_icon.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 310, 70, 100));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11108091_flickr_online_social_media_icon.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 60, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203520_circle_dot_record_round_icon.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, -50, 70, 100));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11108091_flickr_online_social_media_icon.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        gravar();
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void edtAnoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtAnoCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtAnoCarroActionPerformed

    private void edtModeloCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtModeloCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtModeloCarroActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        //seta o icone
        this.setIconImage(Util.getIcone());

        //carregar os dados do usuario
        CarroController controler = new CarroController();
        //consultar os usuarios com o codigo igual ao que recebi
        List<Carro> lista = controler.consultar(0, String.valueOf(idCarro));

        Carro car = lista.get(0);

        //preencher os campos como a variável usu
        edtModeloCarro.setText(car.getMarca());
        edtMarcaCarro.setText(car.getModelo());
        edtPlacaCarro.setText(car.getPlaca());
        edtAnoCarro.setText(String.valueOf(car.getAnoFabricacao()));        
        
    }//GEN-LAST:event_formWindowOpened

    
     private void gravar() {
         
         if (!verificarCampos()) {
        return; 
    }
        
        
        //ler os campos e guardar um objeto
        Carro car = new Carro();
        car.setModelo(edtModeloCarro.getText());
        car.setAnoFabricacao(Integer.parseInt(edtAnoCarro.getText()));
        car.setPlaca(edtPlacaCarro.getText());
        car.setMarca(edtMarcaCarro.getText());
        car.setIdCarro(idCarro);

        
       
        
       
       
        
        
        //enviar para o banco de dados
       CarroController controler = new CarroController();
        if(controler.alterar(car)){
            JOptionPane.showMessageDialog(null, "Carro Alterado");
            this.dispose();
        }
    }
     
     private boolean verificarCampos() {
    if (edtModeloCarro.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Modelo do Carro em branco!");
        return false;
    }
    if (edtMarcaCarro.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Marca do Carro em branco!");
        return false;
    }
    if (edtAnoCarro.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Ano de Fabricação em branco!");
        return false;
    }
    if (edtPlacaCarro.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Placa do Carro em branco!");
        return false;
    }

    return true; 
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAltCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAltCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAltCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAltCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrAltCarro dialog = new FrAltCarro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField edtAnoCarro;
    private javax.swing.JTextField edtMarcaCarro;
    private javax.swing.JTextField edtModeloCarro;
    private javax.swing.JTextField edtPlacaCarro;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnoCarro;
    private javax.swing.JLabel lblMarcaCarro;
    private javax.swing.JLabel lblModeloCarro;
    private javax.swing.JLabel lblPlacaCarro;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
