/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PecaController;
import javax.swing.JOptionPane;
import model.Peca;
import utils.Util;

/**
 *
 * @author aluno.saolucas
 */
public class FrCadPeca extends javax.swing.JDialog {

    /**
     * Creates new form FrCadPeca
     */
    public FrCadPeca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        edtDescricaoPeca = new javax.swing.JTextField();
        lblNomePeca = new javax.swing.JLabel();
        lblDescricaoPeca = new javax.swing.JLabel();
        lblValorPeca = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        edtNomePeca = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        edtValorPeca = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de peças");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(edtDescricaoPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 223, -1));

        lblNomePeca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNomePeca.setText("NOME:");
        jPanel1.add(lblNomePeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        lblDescricaoPeca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDescricaoPeca.setText("DESCRIÇÃO:");
        jPanel1.add(lblDescricaoPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        lblValorPeca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblValorPeca.setText("VALOR:");
        jPanel1.add(lblValorPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        btnVoltar.setBackground(new java.awt.Color(234, 106, 106));
        btnVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        edtNomePeca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtNomePeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomePecaActionPerformed(evt);
            }
        });
        jPanel1.add(edtNomePeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 223, -1));

        btnSalvar.setBackground(new java.awt.Color(234, 106, 106));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));
        jPanel1.add(edtValorPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 223, -1));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setText("CADASTRO DE PEÇAS");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203520_circle_dot_record_round_icon.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, -50, 70, 100));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11108091_flickr_online_social_media_icon.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 60, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203520_circle_dot_record_round_icon.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 260, 70, 100));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11108091_flickr_online_social_media_icon.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void edtNomePecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomePecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomePecaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       this.setIconImage(Util.getIcone()); 
    }//GEN-LAST:event_formWindowOpened

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        gravar();
    }//GEN-LAST:event_btnSalvarMouseClicked

     private void gravar() {
        
          if (!verificarCampos()) {
        return;
    }
         
         
        //ler os campos e guardar um objeto
        Peca peca = new Peca();
        peca.setNome(edtNomePeca.getText());
        double valor = Double.parseDouble(edtValorPeca.getText());
        peca.setValorUnitario(valor);
        peca.setDescricao(edtDescricaoPeca.getText());
        
        
        
        
        //enviar para o banco de dados
        PecaController controler = new PecaController();
        if(controler.inserir(peca)){
            JOptionPane.showMessageDialog(null, "Peça Inserida");
            this.dispose();
        }else{
             JOptionPane.showMessageDialog(null, "Erro ao inserir peça");
        }
    }
    
     private boolean verificarCampos() {
    if (edtNomePeca.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Nome da Peça em branco!");
        return false;
    }
    if (edtValorPeca.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Valor Unitário em branco!");
        return false;
    }
    if (edtDescricaoPeca.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Descrição em branco!");
        return false;
    }

    
    try {
        Double.parseDouble(edtValorPeca.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Valor Unitário inválido! Digite um número.");
        return false;
    }

    return true;
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrCadPeca dialog = new FrCadPeca(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField edtDescricaoPeca;
    private javax.swing.JTextField edtNomePeca;
    private javax.swing.JTextField edtValorPeca;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescricaoPeca;
    private javax.swing.JLabel lblNomePeca;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorPeca;
    // End of variables declaration//GEN-END:variables
}
