/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import controller.PecaController;
import controller.UsuarioController;
import javax.swing.JOptionPane;
import model.Cliente;
import utils.Util;

/**
 *
 * @author aluno.saolucas
 */
public class FrCadCliente extends javax.swing.JDialog {

    /**
     * Creates new form FrCadCliente
     */
    public FrCadCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        edtNomeCliente = new javax.swing.JTextField();
        edtTelefoneCliente = new javax.swing.JTextField();
        edtEmailCliente = new javax.swing.JTextField();
        edtEnderecoCliente = new javax.swing.JTextField();
        lblNomeCliente = new javax.swing.JLabel();
        lblEmailCliente = new javax.swing.JLabel();
        lblEnderecoCliente = new javax.swing.JLabel();
        lblTelefoneCliente2 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtNomeCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        edtNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeClienteActionPerformed(evt);
            }
        });
        jPanel1.add(edtNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 223, -1));
        jPanel1.add(edtTelefoneCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 223, -1));
        jPanel1.add(edtEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 223, -1));
        jPanel1.add(edtEnderecoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 223, -1));

        lblNomeCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNomeCliente.setText("NOME:");
        jPanel1.add(lblNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        lblEmailCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEmailCliente.setText("E-MAIL:");
        jPanel1.add(lblEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        lblEnderecoCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEnderecoCliente.setText("ENDEREÇO:");
        jPanel1.add(lblEnderecoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        lblTelefoneCliente2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTelefoneCliente2.setText("TELEFONE:");
        jPanel1.add(lblTelefoneCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        btnVoltar.setBackground(new java.awt.Color(234, 106, 106));
        btnVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        btnSalvar.setBackground(new java.awt.Color(234, 106, 106));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setText("CADASTRO DE CLIENTES");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11108091_flickr_online_social_media_icon.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -40, 90, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203520_circle_dot_record_round_icon.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, -40, 70, 100));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203520_circle_dot_record_round_icon.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 310, 70, 100));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11108091_flickr_online_social_media_icon.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeClienteActionPerformed

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        gravar();
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    this.setIconImage(Util.getIcone());       
    }//GEN-LAST:event_formWindowOpened
         private void gravar() {
    
        if (!verificarCampos()) {
        return; 
    }
        
        //ler os campos e guardar um objeto
        Cliente cli = new Cliente();
        cli.setNome(edtNomeCliente.getText());
        cli.setTelefone(edtTelefoneCliente.getText());
        cli.setEmail(edtEmailCliente.getText());
        cli.setEndereco(edtEnderecoCliente.getText());
        
       
       
        
        
        //enviar para o banco de dados
        ClienteController controler = new ClienteController();
        if(controler.inserir(cli)){
            JOptionPane.showMessageDialog(null, "Cliente Inserido");
            this.dispose();
        }
    }
         
         
         
         private boolean verificarCampos() {
    if (edtNomeCliente.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Nome em branco!");
        return false;
    }
    if (edtTelefoneCliente.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Telefone em branco!");
        return false;
    }
    if (edtEmailCliente.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo E-mail em branco!");
        return false;
    }
    if (edtEnderecoCliente.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Endereço em branco!");
        return false;
    }

    return true;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrCadCliente dialog = new FrCadCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField edtEmailCliente;
    private javax.swing.JTextField edtEnderecoCliente;
    private javax.swing.JTextField edtNomeCliente;
    private javax.swing.JTextField edtTelefoneCliente;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmailCliente;
    private javax.swing.JLabel lblEnderecoCliente;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblTelefoneCliente2;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
