/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CarroController;
import controller.ClienteController;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Carro;
import model.Cliente;
import utils.Util;

/**
 *
 * @author aluno.saolucas
 */
public class FrCadCarro extends javax.swing.JDialog {

    /**
     * Creates new form FrCadCarro
     */
    public FrCadCarro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        edtModeloCarro = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        edtMarcaCarro = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        edtAnoCarro = new javax.swing.JTextField();
        edtPlacaCarro = new javax.swing.JTextField();
        lblModeloCarro = new javax.swing.JLabel();
        lblAnoCarro = new javax.swing.JLabel();
        lblPlacaCarro = new javax.swing.JLabel();
        lblMarcaCarro = new javax.swing.JLabel();
        lblPlacaCarro1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxFiltro = new javax.swing.JComboBox<>();
        edtFiltro = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro De Carros");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVoltar.setBackground(new java.awt.Color(234, 106, 106));
        btnVoltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        edtModeloCarro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        edtModeloCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtModeloCarroActionPerformed(evt);
            }
        });
        jPanel1.add(edtModeloCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 228, -1));

        btnSalvar.setBackground(new java.awt.Color(234, 106, 106));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));
        jPanel1.add(edtMarcaCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 228, -1));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setText("CADASTRO DE CARROS");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        edtAnoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtAnoCarroActionPerformed(evt);
            }
        });
        jPanel1.add(edtAnoCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 240, 20));
        jPanel1.add(edtPlacaCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 240, -1));

        lblModeloCarro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblModeloCarro.setText("MODELO:");
        jPanel1.add(lblModeloCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        lblAnoCarro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAnoCarro.setText("ANO DE FABRICAÇÃO:");
        jPanel1.add(lblAnoCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        lblPlacaCarro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPlacaCarro.setText("PLACA:");
        jPanel1.add(lblPlacaCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        lblMarcaCarro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMarcaCarro.setText("MARCA:");
        jPanel1.add(lblMarcaCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lblPlacaCarro1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPlacaCarro1.setText("PROPRIETÁRIO:");
        jPanel1.add(lblPlacaCarro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Email", "Telefone", "Endereco"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblClientes);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 520, 110));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203520_circle_dot_record_round_icon.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 380, 70, 100));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11108091_flickr_online_social_media_icon.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 60, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203520_circle_dot_record_round_icon.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, -60, 70, 100));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11108091_flickr_online_social_media_icon.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 60, 60));

        cbxFiltro.setBackground(new java.awt.Color(234, 106, 106));
        cbxFiltro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID igual a", "Nome contendo", "Descricao contendo", " " }));
        jPanel1.add(cbxFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 120, -1));
        jPanel1.add(edtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 240, -1));

        btnPesquisar.setBackground(new java.awt.Color(234, 106, 106));
        btnPesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
        });
        jPanel1.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void edtModeloCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtModeloCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtModeloCarroActionPerformed

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        gravar();
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void edtAnoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtAnoCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtAnoCarroActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(Util.getIcone());
    }//GEN-LAST:event_formWindowOpened

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        pesquisar();
    }//GEN-LAST:event_btnPesquisarMouseClicked
    private void gravar() {

        if (!verificarCampos()) {
        return; 
    }
        
        
        //valido de tem alguma linha selecionada na grade = -1
        if (tblClientes.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione o cliente !");
            return;
        }
        
        //ler os campos e guardar um objeto
        Carro carro = new Carro();
        carro.setModelo(edtModeloCarro.getText());
        carro.setMarca(edtMarcaCarro.getText());
        int anoFabricacao = Integer.parseInt(edtAnoCarro.getText());
        carro.setAnoFabricacao(anoFabricacao);
        carro.setPlaca(edtPlacaCarro.getText());
        
        
        //pego numero da linha selecionada
        int posicaoLinha = tblClientes.getSelectedRow();

        //pego o valor da celula na grade, na coluna 0(codigo)
        String celula = tblClientes.getValueAt(posicaoLinha, 0).toString();

        int idCliente = Integer.parseInt(celula);

        carro.setFkCliente(idCliente); 

        //enviar para o banco de dados
        CarroController controler = new CarroController();
        if (controler.inserir(carro)) {
            JOptionPane.showMessageDialog(null, "Carro Inserido");
            this.dispose();
        }

    }

    private void pesquisar() {
        //pega o modelo da grade com suas colunas
        DefaultTableModel modeloTabela = (DefaultTableModel) tblClientes.getModel();

        //limpa a grade setando o numero de linhas para zero
        modeloTabela.setNumRows(0);

        
        int opcaoFiltro = cbxFiltro.getSelectedIndex();
        String filtro = edtFiltro.getText();

        //consultar banco de dados
        ClienteController controler = new ClienteController();

        List<Cliente> listaClientes = controler.consultar(opcaoFiltro, filtro);

        //preencher a grade
        for (Cliente cli : listaClientes) {
            Object[] linha = {
                cli.getIdCliente(), //0
                cli.getNome(), //1
                cli.getEmail(), //2
                cli.getTelefone(), //3
                cli.getEndereco() //4
            };

            modeloTabela.addRow(linha);

        }
    }
    
    
    private boolean verificarCampos() {
    if (edtModeloCarro.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Modelo do Carro em branco!");
        return false;
    }
    if (edtMarcaCarro.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Marca do Carro em branco!");
        return false;
    }
    if (edtAnoCarro.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Ano de Fabricação em branco!");
        return false;
    }
    if (edtPlacaCarro.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Campo Placa do Carro em branco!");
        return false;
    }

    return true; 
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrCadCarro dialog = new FrCadCarro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxFiltro;
    private javax.swing.JTextField edtAnoCarro;
    private javax.swing.JTextField edtFiltro;
    private javax.swing.JTextField edtMarcaCarro;
    private javax.swing.JTextField edtModeloCarro;
    private javax.swing.JTextField edtPlacaCarro;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnoCarro;
    private javax.swing.JLabel lblMarcaCarro;
    private javax.swing.JLabel lblModeloCarro;
    private javax.swing.JLabel lblPlacaCarro;
    private javax.swing.JLabel lblPlacaCarro1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
