/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import utils.Util;

/**
 *
 * @author Administrador
 */
public class FrMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrMenu
     */
    public FrMenu() {
        initComponents();
          this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCadCliente = new javax.swing.JButton();
        btnConCarro = new javax.swing.JButton();
        btnCadServico = new javax.swing.JButton();
        btnCadCarro = new javax.swing.JButton();
        btnCadOrdemServico = new javax.swing.JButton();
        btnConCliente = new javax.swing.JButton();
        btnConPeca = new javax.swing.JButton();
        btnConServico = new javax.swing.JButton();
        btnCadPeca = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(235, 235, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSair.setBackground(new java.awt.Color(234, 106, 106));
        btnSair.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSair.setText("SAIR");
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 240, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Seja Bem Vindo!!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11108091_flickr_online_social_media_icon.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -40, 60, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203520_circle_dot_record_round_icon.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, -40, 70, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11108091_flickr_online_social_media_icon.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 140, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2203520_circle_dot_record_round_icon.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 400, 70, 100));

        btnCadCliente.setBackground(new java.awt.Color(234, 106, 106));
        btnCadCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCadCliente.setText("CADASTRAR CLIENTE");
        btnCadCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadClienteMouseClicked(evt);
            }
        });
        jPanel1.add(btnCadCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 240, 40));

        btnConCarro.setBackground(new java.awt.Color(234, 106, 106));
        btnConCarro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnConCarro.setText("CONSULTAR CARRO");
        btnConCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConCarroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConCarroMouseEntered(evt);
            }
        });
        jPanel1.add(btnConCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 240, 40));

        btnCadServico.setBackground(new java.awt.Color(234, 106, 106));
        btnCadServico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCadServico.setText("CADASTRAR SERVIÇO");
        btnCadServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadServicoMouseClicked(evt);
            }
        });
        btnCadServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadServicoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 240, 40));

        btnCadCarro.setBackground(new java.awt.Color(234, 106, 106));
        btnCadCarro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCadCarro.setText("CADASTRAR CARRO");
        btnCadCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadCarroMouseClicked(evt);
            }
        });
        jPanel1.add(btnCadCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 240, 40));

        btnCadOrdemServico.setBackground(new java.awt.Color(234, 106, 106));
        btnCadOrdemServico.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnCadOrdemServico.setText("CADASTRAR ORDEM DE SEVIÇO");
        btnCadOrdemServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadOrdemServicoMouseClicked(evt);
            }
        });
        btnCadOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadOrdemServicoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadOrdemServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 240, 40));

        btnConCliente.setBackground(new java.awt.Color(234, 106, 106));
        btnConCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnConCliente.setText("CONSULTAR CLIENTE");
        btnConCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConClienteMouseClicked(evt);
            }
        });
        jPanel1.add(btnConCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 240, 40));

        btnConPeca.setBackground(new java.awt.Color(234, 106, 106));
        btnConPeca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnConPeca.setText("CONSULTAR PEÇA");
        btnConPeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConPecaMouseClicked(evt);
            }
        });
        btnConPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConPecaActionPerformed(evt);
            }
        });
        jPanel1.add(btnConPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 240, 40));

        btnConServico.setBackground(new java.awt.Color(234, 106, 106));
        btnConServico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnConServico.setText("CONSULTAR  SERVIÇO");
        btnConServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConServicoMouseClicked(evt);
            }
        });
        jPanel1.add(btnConServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 240, 40));

        btnCadPeca.setBackground(new java.awt.Color(234, 106, 106));
        btnCadPeca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCadPeca.setText("CADASTRAR PEÇA");
        btnCadPeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadPecaMouseClicked(evt);
            }
        });
        btnCadPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPecaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 240, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeP.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, -70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadOrdemServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadOrdemServicoActionPerformed

    private void btnCadClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadClienteMouseClicked
       FrCadCliente telaCadCliente = new FrCadCliente(this, rootPaneCheckingEnabled);
       telaCadCliente.setVisible(true);
    }//GEN-LAST:event_btnCadClienteMouseClicked

    private void btnCadServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadServicoMouseClicked
       FrCadServico telaCadServico = new FrCadServico(this, rootPaneCheckingEnabled);
       telaCadServico.setVisible(true);
    }//GEN-LAST:event_btnCadServicoMouseClicked

    private void btnCadCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadCarroMouseClicked
       FrCadCarro telaCadCarro = new FrCadCarro(this, rootPaneCheckingEnabled);
       telaCadCarro.setVisible(true);
    }//GEN-LAST:event_btnCadCarroMouseClicked

    private void btnCadOrdemServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadOrdemServicoMouseClicked
       FrCadOrdem telaCadOrdemServico = new FrCadOrdem(this, rootPaneCheckingEnabled);
     telaCadOrdemServico.setVisible(true);
    }//GEN-LAST:event_btnCadOrdemServicoMouseClicked

    private void btnConClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConClienteMouseClicked
       FrConCliente telaConCliente = new FrConCliente(this, rootPaneCheckingEnabled);
       telaConCliente.setVisible(true);
    }//GEN-LAST:event_btnConClienteMouseClicked

    private void btnConCarroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConCarroMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConCarroMouseEntered

    private void btnConCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConCarroMouseClicked
       FrConCarro telaConCarro = new FrConCarro(this, rootPaneCheckingEnabled);
       telaConCarro.setVisible(true);
    }//GEN-LAST:event_btnConCarroMouseClicked

    private void btnConPecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConPecaMouseClicked
       FrConPeca telaConPeca = new FrConPeca(this, rootPaneCheckingEnabled);
       telaConPeca.setVisible(true);
    }//GEN-LAST:event_btnConPecaMouseClicked

    private void btnConServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConServicoMouseClicked
      FrConServico telaConServico = new FrConServico(this, rootPaneCheckingEnabled);
       telaConServico.setVisible(true);
    }//GEN-LAST:event_btnConServicoMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
       this.dispose();
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnCadPecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadPecaMouseClicked
       FrCadPeca telaCadPeca = new FrCadPeca(this, rootPaneCheckingEnabled);
       telaCadPeca.setVisible(true);
    }//GEN-LAST:event_btnCadPecaMouseClicked

    private void btnCadPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadPecaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadServicoActionPerformed
        FrCadServico telaCadServico = new FrCadServico(this, rootPaneCheckingEnabled);
       telaCadServico.setVisible(true);
    }//GEN-LAST:event_btnCadServicoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      this.setIconImage(Util.getIcone()); 
    }//GEN-LAST:event_formWindowOpened

    private void btnConPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConPecaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadCarro;
    private javax.swing.JButton btnCadCliente;
    private javax.swing.JButton btnCadOrdemServico;
    private javax.swing.JButton btnCadPeca;
    private javax.swing.JButton btnCadServico;
    private javax.swing.JButton btnConCarro;
    private javax.swing.JButton btnConCliente;
    private javax.swing.JButton btnConPeca;
    private javax.swing.JButton btnConServico;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
